-- Oracle init script for baton-sql demo
-- Run against XEPDB1 pluggable database

-- Users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    status VARCHAR2(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Groups table
CREATE TABLE groups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Group memberships (many-to-many)
CREATE TABLE group_memberships (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    group_id NUMBER NOT NULL,
    role VARCHAR2(50) DEFAULT 'member',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_memberships_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_group UNIQUE (user_id, group_id)
);

-- Sample data: Users
INSERT INTO users (email, first_name, last_name, status) VALUES ('alice@example.com', 'Alice', 'Anderson', 'active');
INSERT INTO users (email, first_name, last_name, status) VALUES ('bob@example.com', 'Bob', 'Baker', 'active');
INSERT INTO users (email, first_name, last_name, status) VALUES ('carol@example.com', 'Carol', 'Chen', 'active');
INSERT INTO users (email, first_name, last_name, status) VALUES ('david@example.com', 'David', 'Davis', 'inactive');
INSERT INTO users (email, first_name, last_name, status) VALUES ('eve@example.com', 'Eve', 'Edwards', 'active');
INSERT INTO users (email, first_name, last_name, status) VALUES ('frank@example.com', 'Frank', 'Fisher', 'suspended');

-- Sample data: Groups
INSERT INTO groups (name, description) VALUES ('engineering', 'Engineering team');
INSERT INTO groups (name, description) VALUES ('sales', 'Sales department');
INSERT INTO groups (name, description) VALUES ('admin', 'System administrators');
INSERT INTO groups (name, description) VALUES ('finance', 'Finance and accounting');
INSERT INTO groups (name, description) VALUES ('hr', 'Human resources');

-- Sample data: Memberships
INSERT INTO group_memberships (user_id, group_id, role) VALUES (1, 1, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (1, 3, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (2, 1, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (3, 2, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (3, 4, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (4, 2, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (5, 1, 'member');
INSERT INTO group_memberships (user_id, group_id, role) VALUES (5, 5, 'member');

COMMIT;
